Visual Studio Code (1.93.0, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension Version: 2024.11.1.
Platform: linux (x64).
Temp Storage folder ~/.config/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.1
Workspace folder ~/hse/machine_learning, Home = /home/yoshee
11:41:30.777 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.7) for '~/hse/machine_learning/sem9_classwork.ipynb' (disableUI=true)
11:41:30.801 [warn] Failed to get activated env vars for /bin/python3 in 25ms
11:41:30.804 [warn] Failed to get activated env vars for /bin/python3 in 17ms
11:41:30.811 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
11:41:30.825 [warn] Failed to get activated env vars for /bin/python3 in 10ms
11:41:30.834 [info] Process Execution: /bin/python3 -m pip list
11:41:30.840 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:41:30.846 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v3ab8d187530908bcc7ffcaa03e6f90290380a8502.json
    > cwd: //home/~/hse/machine_learning
11:41:30.867 [info] Process Execution: /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:41:31.702 [info] Kernel successfully started
11:41:31.711 [info] Process Execution: /bin/python3 /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/pythonFiles/printJupyterDataDir.py
11:44:05.472 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.7) for '~/hse/machine_learning/sem10.ipynb' (disableUI=false)
11:44:05.492 [warn] Failed to get activated env vars for /bin/python3 in 16ms
11:44:05.498 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:44:05.509 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v3c72cd1a21ec6c46f0e92544cdc2da99126827c41.json
    > cwd: //home/~/hse/machine_learning
11:44:06.149 [info] Kernel successfully started
11:44:06.278 [warn] Cell completed with errors nu [Error]: name 'pd' is not defined
    at n.execute (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:297:4958) {
  ename: 'NameError',
  evalue: "name 'pd' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[1], line 1\x1B[0m\n' +
      "\x1B[0;32m----> 1\x1B[0m data \x1B[38;5;241m=\x1B[39m \x1B[43mpd\x1B[49m\x1B[38;5;241m.\x1B[39mread_csv(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m./DataSet2_1.csv\x1B[39m\x1B[38;5;124m'\x1B[39m,sep\x1B[38;5;241m=\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m|\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[1;32m      2\x1B[0m \x1B[38;5;66;03m# разбиваем данные на тренировочную и тестовую выборку\x1B[39;00m\n' +
      "\x1B[1;32m      3\x1B[0m X \x1B[38;5;241m=\x1B[39m data\x1B[38;5;241m.\x1B[39mdrop(columns\x1B[38;5;241m=\x1B[39m[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mfraud\x1B[39m\x1B[38;5;124m'\x1B[39m])\n",
    "\x1B[0;31mNameError\x1B[0m: name 'pd' is not defined"
  ]
}
11:54:53.221 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.7) for '~/Downloads/Untitled6.ipynb' (disableUI=true)
11:54:53.269 [warn] Failed to get activated env vars for /bin/python3 in 47ms
11:54:53.281 [info] Process Execution: /bin/python3 -m pip list
11:54:53.285 [warn] Failed to get activated env vars for /bin/python3 in 60ms
11:54:53.296 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:54:53.312 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v38889cf9455be49821171e8003ba8f74bbccfb25f.json
    > cwd: //home/~/Downloads
11:54:53.325 [info] Process Execution: /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:54:53.944 [info] Kernel successfully started
11:55:08.048 [info] Dispose Kernel '~/Downloads/Untitled6.ipynb' associated with '~/Downloads/Untitled6.ipynb'
12:15:22.735 [info] Starting Kernel (Python Path: /bin/python3, Unknown, 3.12.7) for '~/hse/machine_learning/sem_8_classwork.ipynb' (disableUI=true)
12:15:22.785 [warn] Failed to get activated env vars for /bin/python3 in 49ms
12:15:22.793 [info] Process Execution: /bin/python3 -m pip list
12:15:22.794 [warn] Failed to get activated env vars for /bin/python3 in 55ms
12:15:22.803 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
12:15:22.814 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v326939c34b8093ee97da3b777d8efa2b2dac0cdd2.json
    > cwd: //home/~/hse/machine_learning
12:15:22.837 [info] Process Execution: /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:15:23.454 [info] Kernel successfully started
22:57:42.542 [info] Dispose Kernel '~/hse/machine_learning/sem9_classwork.ipynb' associated with '~/hse/machine_learning/sem9_classwork.ipynb'
22:57:42.549 [info] Dispose Kernel '~/hse/machine_learning/sem10.ipynb' associated with '~/hse/machine_learning/sem10.ipynb'
22:57:42.556 [info] Dispose Kernel '~/Downloads/Untitled6.ipynb' associated with '~/Downloads/Untitled6.ipynb'
22:57:42.556 [info] Dispose Kernel '~/hse/machine_learning/sem_8_classwork.ipynb' associated with '~/hse/machine_learning/sem_8_classwork.ipynb'
22:57:42.605 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v326939c34b8093ee97da3b777d8efa2b2dac0cdd2.json for pid 107785 Canceled (FileSystemError): Canceled
    at Function.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:7311)
    at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3977)
    at Jc.delete (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:239:15273)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
22:57:42.607 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v3c72cd1a21ec6c46f0e92544cdc2da99126827c41.json for pid 15775 Canceled (FileSystemError): Canceled
    at Function.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:7311)
    at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3977)
    at Jc.delete (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:239:15273)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
22:57:42.607 [warn] Failed to delete connection file file:///home/~/.local/share/jupyter/runtime/kernel-v3ab8d187530908bcc7ffcaa03e6f90290380a8502.json for pid 7217 Canceled (FileSystemError): Canceled
    at Function.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:7311)
    at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:3977)
    at Jc.delete (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:239:15273)
    at /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:303:469 {
  code: 'Unknown'
}
